.travis.yml
R/glHandle.R
R/handling.R
man/seppop.Rd
tests/testthat/test-seppop.R
tests/testthat/test_subset.R

This adds two things
1. The ability to specify strata when using `seppop` (akin to what I added in `genind2genpop`)
2. Setting the `NOT_CRAN` environment variable in travis so that tests will run on travis. They will always skip on cran, but this makes sure that everything behind the scenes are working so you don't have to run tests locally.

Seppop strata

---

R/glHandle.R

I realized that the subsetter was converting all the raw bits to integers before subsetting. If the subsetting happens before the integer conversion, we see a speedup in the data with large numbers of SNPs.
Protocol the same as #48.
Old Method:
```
Unit: milliseconds
expr        min         lq       mean     median         uq       max neval cld
x[, the_loci]   5.185082   5.678802   7.731961   6.007779   7.175650 149.25734   200 a
y[, the_loci]   5.902340   6.467108   7.996073   7.000335   8.356582  39.65144   200 a
z[, the_loci]  22.080076  26.274703  30.389466  28.280454  31.426308 189.91701   200  b
zz[, the_loci] 142.129836 165.874361 235.373325 191.655808 309.998984 480.83209   200   c
```
New Method:
```
Unit: milliseconds
expr       min         lq       mean     median         uq …
```

Small speedup to snpbin

---

ChangeLog
R/glHandle.R
tests/testthat/test_genlight.R

This will fix issue #83
I have changed the subsetter for both SNPbin and genlight objects.

SNPbin fix

---

man/find.clusters.Rd

'conserv' was changed to 'goodfit' in the description of 'criterion' argument

Typo in find.clusters.Rd

---

R/chooseCN.R

Dear Dr. Jombart,
I tried to build a connection network for sPCA and found that maybe there is a typo in `chooseCN` code for the type 7 graph (inverse distance).
To avoid infinite spatial proximities you substitute the minimum distance between points with a small threshold:
`    thres <- mean(cn)/1e8`                 # cn at this step is a distance matrix
`    if(dmin > thres) dmin <- thres`
If somebody will choose very small dmin (e.g., `dmin = 0`) this condition will be FALSE.
Hence, at the next step  `cn <- 1/(cn^a)`  we will obtain *Inf* values and at the end `mat2listw` will return an error.
I suppose that condition in `if(dmin > thres) dmin <- thres`
should be changed to `if(dmin < thres) dmin <- thres`
https://github.com/thibautjombart/adegenet/blob/96f8cb2659a81c61e4afad725bf57cf01 …

chooseCN fix - Inverse distance, infinite values

---

R/glFunctions.R

Seems to be caused by copy-paste programming.
Replacing NA values in the same vector `a` twice does not seem meaningful.

fix a typo affecting glPca(center & scale)

---

R/find.clust.R

The function `adegenet::find.clusters` appears to be throwing a warning.
library(poppr)
data("Pinf", package = "poppr")
Pinf.l <- seppop(Pinf)
find.clusters(Pinf.l[[1]], max.n = 20, n.pca = 10, scale = FALSE, choose.n.clust=F, quiet=T)
The "ward" method has been renamed to "ward.D"; note new "ward.D2"
This appears to be due to `stats::hclust` changing its method name from 'ward' to 'ward.D'. This PR updates the call in `adegenet::find.clusters` so the warning is not thrown.

changed ward to ward.D in find.clusters.data.frame

---

R/haploGen.R
tests/testthat/test_haploGen.R

This will fix #179 as per Emmanuel's suggestion, but I've additionally discovered that `as.igraph.haploGen()` is also broken; I have not attempted to fix this.
I've also added a test for simple functionality of haploGen, but not necessarily for accuracy.

Fix haploGen

---

.travis.yml

This will test both R and R-devel with caching, so the builds will go faster and we won't get deprecation warnings anymore.

update travis to use native R with caching

---

R/basicMethods.R
tests/testthat/test_accessors.R

The subsettors were giving off one warning for each
incorrect individual/locus/pop. I fixed this and
added some tests.

update subsettor warnings and add tests

---

R/find.clust.R

The issue was that max.n.clust was set at round(n/10) for the entire data set, but the
clustering step would bork when it was told to find
more clusters than there were samples.
This fix sets the maximum number of clusters for
each popualtion to be n - 1

attempt to fix #184

---

R/import.R

adding the "^" prevents the search from matching substrings. This was brought up in #218

force exact match for data cromulence in df2genind

---

ChangeLog
DESCRIPTION
R/glHandle.R
R/handling.R
man/seppop.Rd
tests/testthat/test-seppop.R

This was brought up in https://github.com/grunwaldlab/poppr/issues/189. Basically, if any populations assignments are set to `NA`, then `seppop()` will erroneously insert those individuals in all of the subsequent populations, resulting in errors down the road. 
This PR fixes that by adding a `keepNA` argument and warning the user if there are missing population assignments.

Allow seppop to handle missing population assignment

---

.travis.yml
DESCRIPTION
R/accessors.R
R/basicMethods.R
man/accessors.Rd
tests/testthat/test_accessors.R

A bug/feature that was fixed/added from #234 / #235 was changing the `@loc.n.all` slot so that it would report the number of alleles present in the population instead of the number of columns/locus. It turned out that this was a bad idea because it broke the `alleles()<-` accessor (not to mention poppr). 
To fix this, I've implemented an option `onlyObserved` in the `nAll()` accessor, which will return the observed number of alleles when `TRUE`, but defaults to `FALSE`, which returns the number of columns per locus. This has been set to `TRUE` in the `summary()` function to make sure the promise of #234 is kept.

Make loc.n.all backwards compatible

---

ChangeLog
R/import.R

Hi Thibaut,
how are things? We are analyzing some RADseq data in our lab and could not transform a vcf files to genind objects. `df2genind` run out of memory and R stalled. 
So I made some improvements to `df2genind`. This code seems to work as intended, but maybe you have to check with some more tricky data sets to test it more thorough. 
E.g. the following code take now .2 seconds instead of 6 seconds on my machine.
```
library(adegenet)
library(vcfR)
data(vcfR_example)
my_genind <- vcfR2genind(vcf)
```
It should also be possible to transform larger data sets, which should be useful for quite a few people. 
I also cleaned up some code, e.g. replace `paste()` with `paste0()` or using `lengths(x)` instead of `sapply(x, length)`. 
Cheers, 
Klaus

Speed up df2genind

---

ChangeLog
DESCRIPTION
R/basicMethods.R
R/glHandle.R
R/handling.R
tests/testthat/test-seppop.R

This will fix #270. @rdinnager, can you check this with your analysis and confirm that it does what you expect? This is what I get:
``` r
library(adegenet)
#> Loading required package: ade4
#> Registered S3 method overwritten by 'spdep':
#>   method   from
#>   plot.mst ape
#> 
#>    /// adegenet 2.1.2 is loaded ////////////
#> 
#>    > overview: '?adegenet'
#>    > tutorials/doc/questions: 'adegenetWeb()' 
#>    > bug reports/feature requests: adegenetIssues()
x <- matrix(sample(0:2, 40*10, replace = TRUE), ncol = 40, nrow = 10) 
x <- new("genlight", x)
x
#>  /// GENLIGHT OBJECT /////////
#> 
#>  // 10 genotypes,  40 binary SNPs, size: 16.9 Kb
#>  0 (0 %) missing data
#> 
#>  // Basic content
#>    @gen: list of 10 SNPbin
#> 
#>  // Optional content
#>    @other: a list containing: …
```

Add pop argument to genlight bracket accessor

---

ChangeLog
DESCRIPTION
R/import.R
man/fasta2genlight.Rd
man/read.PLINK.Rd

It turns out that `read.PLINK()` and `fasta2genlight()` were still harboring the demon `parallel=require('parallel')`. Since parallel computation did not _really_ speed things up, I've set them to default as `FALSE` for everyone. 
This will address #313 until we have a better solution.

Set all parallel = FALSE

---

DESCRIPTION
R/xvalDapc.R

This is an extra sanity check to make sure https://github.com/thibautjombart/adegenet/issues/322 cannot happen

add sanity check to n.pca.max to default to max value if vector

---

DESCRIPTION
R/spca.R

Fixes a bug where `summary.spca` only worked on `spca` objects derived from `genind` and `genpop` objects.  Now `summary.spca` and `screeplot.spca` both work when matrices and data frames are used for `spca`.
Resolves #328

summmary.spca bug fix for matrices and data frames

---

.github/workflows/recheck.yml
ChangeLog
DESCRIPTION
R/glHandle.R
tests/testthat/test_genlight.R

Fix bug where genlight subsetting with no loci specified results in an extra bit

---

R/spca.R
man/spca.Rd
spca_randtest(modified)

`multispati` is now deprecated in `ade4` and must be imported from `adespatial`.

Update of the original package for the imported 'multispati' function
