- R/import.R
- tests/testthat/test_import.R
I also added a test function and check that coerces ind.names to character
> solves #96

- R/import.R
> Speedup missing import

- ChangeLog
- DESCRIPTION
- R/import.R
- tests/testthat/test_import.R
> read.genepop with individual names

- DESCRIPTION
> Add Libor Morkovsky to contributors

- DESCRIPTION
- R/import.R
- man/fasta2DNAbin.Rd
> allow fasta2DNABin to accept a file connection

- R/SNPbin.R
For a while now, poppr's been getting [an error on solaris sparc](https://www.r-project.org/nosvn/R.check/r-patched-solaris-sparc/poppr-00check.html):
```
checking examples ... ERROR
Running examples in ‘poppr-Ex.R’ failed
The error most likely occurred in:
> ### Name: bitwise.dist
> ### Title: Calculate a dissimilarity distance matrix for SNP data.
> ### Aliases: bitwise.dist
> 
> ### ** Examples
> 
> set.seed(999)
> x <- glSim(n.ind = 10, n.snp.nonstruc = 5e2, n.snp.struc = 5e2, ploidy = 2)
*** caught segfault ***
address 8800000, cause 'memory not mapped'
Error in .bin2raw(temp) : 'translateChar' must be called on a CHARSXP
Calls: glSim ... FUN -> new -> initialize -> initialize -> .bin2raw -> .C
Execution halted
```
I've replaced the call to the C function `binIntToBytes` with the …
> update .bin2raw to use base R bit packing

- DESCRIPTION
- R/dist.genlight.R
Creating distance matrices from genlight objects was a little mysterious to me. So I thought some documentation may help. Thank you!
> Dist.genlight

- R/compoplot.R
- tests/testthat/test_compoplot.R
This will fix #186 
It's currently erroring, but that's travis' fault; not mine.
> Add palette_parser (unexported) 

- R/auxil.R
- R/chooseCN.R
- R/dapc.R
- R/dist.genpop.R
- R/find.clust.R
- R/gengraph.R
- R/glFunctions.R
- R/import.R
- R/monmonier.R
- R/seqTrack.R
- R/zzz.R
- tests/testthat/test-findclust.R
This adds a test for find.clusters. Since this involves user interaction, I've created a workaround by defining a custom connection for `readLines()` that defaults to `stdin()`, so it shouldn't affect user interface. 
@thibautjombart, is this okay with you?
> Add test for find.clusters; set custom connection

- R/showmekittens.R
I have altered the kitties. Pray I do not alter them any further.
> update vacuum, add eclipse and nom

- R/snapclust.choose.k.R
- tests/testthat/test_snapclust.R
There is pretty much only one use-case for this, but hey, it would be useful if anyone else were to extend the genind object ᕕ( ᐛ )ᕗ
> Allow snapclust to work on objects that inherit genind objects

- .gitignore
- ChangeLog
- R/import.R
- tests/testthat/test_import.R
> Ploidy warning

- tutorials/tutorial-dapc.Rnw
- tutorials/tutorial-snapclust.Rnw
Hello, congrats on getting your `snapclust()` paper out! I was thinking about trying it on a couple projects I'm working on. But I work on fungi and fungus-like plant pathogens where Hardy-Weinberg is not necessarily met. So perhaps I should stick to DAPC? As I worked through your tutorials I think I found a few typos so I've tried to put together a PR. It builds with 2 WARNINGS, but those were there when I forked the repo. Also, I did not rebuild the pdfs. Wasn't sure how you do that but I saw `tutorials` was in your `.Rbuildignore`.
Thank you!
Brian
> caught typos in snapclust and dapc tutorials

- ChangeLog
- DESCRIPTION
- R/import.R
- R/zzz.R
- man/df2genind.Rd
- tests/testthat/test_import.R
> Adding an option to df2genind to skip the most time-consuming step. 

- DESCRIPTION
Didn't occur to me until now that I might need to make a pull request for the addition of my name (Rebecca DeCamp) as a contributor, so I hope this is okay!
> Updated DESCRIPTION

- spca_randtest(modified)
This is a second attempt at #247 and addresses issue #246
> Modified SPCA randtest

- .Rbuildignore
- CRAN-RELEASE
- cran-comments.md
This is in preparation for version 2.1.2 on CRAN. I'll track all the correspondence here.
> CRAN release

- R/import.R
> update warning messages to be clearer

- R/sequences.R
- tests/testthat/test_conversion.R
This is a fix for R 4.0. It was never previously caught because this part of the code has not been tested.
> use inherits instead of class(x) ==

- R/find.clust.R
A user of our website found this. Thanks!
> Closing parenthesis in find.clusters() choose the number of clusters

- CRAN-RELEASE
- ChangeLog
- DESCRIPTION
- cran-comments.md
- man/H3N2.Rd
- man/dapcIllus.Rd
- man/doc_C_routines.Rd
- man/eHGDP.Rd
- man/hybridtoy.Rd
- man/microbov.Rd
- man/nancycats.Rd
- man/rupica.Rd
- man/sim2pop.Rd
- man/spcaIllus.Rd
- man/swallowtails.Rd
This is largely a maintenance update. 
See #270, #254, #255, #274, #275, #283
> release version 2.1.3

- DESCRIPTION
- R/snapclust.R
- R/snapclust.choose.k.R
- man/snapclust.Rd
- man/snapclust.choose.k.Rd
Should address https://github.com/thibautjombart/adegenet/issues/286
> adding doc for snapclust

- .github/workflows/R-CMD-check.yaml
- CRAN-RELEASE
- ChangeLog
- DESCRIPTION
- R/snapclust.R
- R/snapclust.choose.k.R
- README.md
- cran-comments.md
- man/snapclust.Rd
- man/snapclust.choose.k.Rd
> prepare for CRAN release

- ChangeLog
- R/handling.R
- tests/testthat/test-genind2genpop.R
> fix bug in hybridize via tab method for genpop

- R/find.clust.R
- man/find.clusters.Rd
fixing default parameter to reflect the documentation and making it consistent with the alternative object methods.
This relates to #362
> fixing find.clust.R
